### ISSUE TITLE
Crash on breeding with feeding trough mods

### ISSUE THREAD

**Issue by Miner239** [Majrusz/MajruszsAccessories#18]
[crash-2023-07-27_03.06.57-server.txt](https://github.com/Majrusz/MajruszsAccessories/files/12176862/crash-2023-07-27_03.06.57-server.txt)
Clean test crash report: [crash-2023-07-27_03.24.17-server.txt](https://github.com/Majrusz/MajruszsAccessories/files/12176924/crash-2023-07-27_03.24.17-server.txt)

Game crashes when animals fed by feeding troughs try to spawn a baby animal.

This crash happened with Animal Feeding Trough mod, however, it also happens with Quark's trough.

**Comment by Majrusz** [comment]
Thanks for the report, I fixed that in the library https://github.com/Majrusz/MajruszLibrary/pull/27/commits/db935b4ae9834bd5899e2890319b9f5186b65365 and soon I will release new mod version

**Comment by Majrusz** [comment]
Hi again, 1.2.3 has been released and it should not be an issue anymore
