### ISSUE TITLE
Mod has failed to load. Version 1.18.1-0.4.0 (Error Found com/mlib/config/confighandler)

### ISSUE THREAD

**Issue by DSAH1997** [Majrusz/MajruszsAccessories#2]
Time: 20/12/2021, 18:20
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:69) ~[forge-1.18.1-39.0.5-universal.jar%23159!:?] {re:classloading}
	at net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:183) ~[forge-1.18.1-39.0.5-universal.jar%23159!:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$new$1(Minecraft.java:553) ~[client-1.18.1-20211210.034407-srg.jar%23155!:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.Util.m_137521_(Util.java:569) ~[client-1.18.1-20211210.034407-srg.jar%23155!:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:547) ~[client-1.18.1-20211210.034407-srg.jar%23155!:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.LoadingOverlay.m_6305_(LoadingOverlay.java:196) ~[client-1.18.1-20211210.034407-srg.jar%23155!:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:1254) ~[client-1.18.1-20211210.034407-srg.jar%23155!:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1040) ~[client-1.18.1-20211210.034407-srg.jar%23155!:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:660) ~[client-1.18.1-20211210.034407-srg.jar%23155!:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.1-20211210.034407-srg.jar%23155!:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.18.1-39.0.5.jar%2323!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90) [bootstraplauncher-0.1.17.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?] {}
-- MOD majruszs_accessories --
Details:
	Caused by 0: java.lang.NoClassDefFoundError: com/mlib/config/ConfigHandler
		at com.majruszsaccessories.MajruszsAccessories.<clinit>(MajruszsAccessories.java:23) ~[majruszsaccessories-1.18.1-0.4.0.jar%23110!:0.4.0] {re:classloading}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[javafmllanguage-1.18.1-39.0.5.jar%23157!:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[fmlcore-1.18.1-39.0.5.jar%23156!:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

	Mod File: majruszsaccessories-1.18.1-0.4.0.jar
	Failure message: Majrusz's Accessories (majruszs_accessories) has failed to load correctly
		java.lang.NoClassDefFoundError: com/mlib/config/ConfigHandler
	Mod Version: 0.4.0
	Mod Issue URL: https://github.com/Majrusz/MajruszsAccessories/issues
	Exception message: java.lang.ClassNotFoundException: com.mlib.config.ConfigHandler
Stacktrace:
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:132) ~[securejarhandler-0.9.54.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:132) ~[securejarhandler-0.9.54.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at com.majruszsaccessories.MajruszsAccessories.<clinit>(MajruszsAccessories.java:23) ~[majruszsaccessories-1.18.1-0.4.0.jar%23110!:0.4.0] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[javafmllanguage-1.18.1-39.0.5.jar%23157!:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[fmlcore-1.18.1-39.0.5.jar%23156!:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1388795952 bytes (1324 MiB) / 2348810240 bytes (2240 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 10
	Microarchitecture: Coffee Lake
	Frequency (GHz): 3.70
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce GTX 1070
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1b81
	Graphics card #0 versionInfo: DriverVersion=30.0.14.9613
	Graphics card #1 name: NVIDIA GeForce RTX 2060
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 4095.00
	Graphics card #1 deviceId: 0x1f08
	Graphics card #1 versionInfo: DriverVersion=30.0.14.9613
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.40
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 16384.00
	Memory slot #2 clockSpeed (GHz): 2.40
	Memory slot #2 type: DDR4
	Virtual memory max (MB): 61684.71
	Virtual memory used (MB): 54687.90
	Swap memory total (MB): 29000.29
	Swap memory used (MB): 2577.50
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	OptiFine Version: OptiFine_1.18.1_HD_U_H4
	OptiFine Build: 20211212-175054
	Render Distance Chunks: 12
	Mipmaps: 1
	Anisotropic Filtering: 2
	Antialiasing: 0
	Multitexture: true
	Shaders: null
	OpenGlVersion: 3.2.0 NVIDIA 496.13
	OpenGlRenderer: NVIDIA GeForce RTX 2060/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12
	ModLauncher: 9.0.7+91+master.8569cdf
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 OptiFine TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		kotori_scala@2.13.7-build-2
		javafml@null
	Mod List: 
		supermartijn642configlib-1.0.9-mc1.18.jar         |SuperMartijn642's Config Lib  |supermartijn642configlib      |1.0.9               |COMMON_SET|Manifest: NOSIGNATURE
		AdditionalEnchantedMiner-1.18.1-18.2.jar          |QuarryPlus                    |quarryplus                    |18.2                |COMMON_SET|Manifest: 1a:13:52:63:6f:dc:0c:ad:7f:8a:64:ac:46:58:8a:0c:90:ea:2c:5d:11:ac:4c:d4:62:85:c7:d1:00:fa:9c:76
		endportalrecipe_1.18.1-2.6.jar                    |End Portal Recipe             |endportalrecipe               |2.6                 |COMMON_SET|Manifest: NOSIGNATURE
		simplemagnets-1.1.3-mc1.18.jar                    |Simple Magnets                |simplemagnets                 |1.1.3               |COMMON_SET|Manifest: NOSIGNATURE
		DeathCounter-1.18-1.2.1.jar                       |Death Counter                 |deathcounter                  |1.2.1               |COMMON_SET|Manifest: NOSIGNATURE
		UtilitiX-1.18-0.3.1.jar                           |UtilitiX                      |utilitix                      |1.18-0.3.1          |COMMON_SET|Manifest: NOSIGNATURE
		kingvillager-1.9.1.jar                            |The King of the Villagers     |kingvillager                  |1.9.1               |COMMON_SET|Manifest: NOSIGNATURE
		torohealth-1.18-forge-2.jar                       |ToroHealth                    |torohealth                    |1.18-forge-2        |COMMON_SET|Manifest: NOSIGNATURE
		infcoal-1.18-1.0.jar                              |Infinite Coal                 |infcoal                       |1.18-1.0            |COMMON_SET|Manifest: NOSIGNATURE
		essentials-1.18-2.13.0.jar                        |Essentials                    |essentials                    |1.18-2.13.0         |COMMON_SET|Manifest: NOSIGNATURE
		villagernames_1.18.1-3.5.jar                      |Villager Names                |villagernames                 |3.5                 |COMMON_SET|Manifest: NOSIGNATURE
		Placebo-1.18.1-6.0.1.jar                          |Placebo                       |placebo                       |6.0.1               |COMMON_SET|Manifest: NOSIGNATURE
		forge-branders-spawnermod-1.18-1.8.14.jar         |Enhanced Mob Spawners         |spawnermod                    |1.8.14              |COMMON_SET|Manifest: NOSIGNATURE
		staretilltheygrow-1.18.1-1.1.1.jar                |Stare Till They Grow!         |staretilltheygrow             |1.18.1-1.1.1        |COMMON_SET|Manifest: NOSIGNATURE
		Customized-Dungeon-Loot-1.17.x-(v.2.1.0).jar      |Customized Dungeon Loot       |cdl                           |2.1.0               |COMMON_SET|Manifest: NOSIGNATURE
		jeed-1.18-1.6.jar                                 |Just Enough Effect Description|jeed                          |1.18-1.6            |COMMON_SET|Manifest: NOSIGNATURE
		skeletonhorsespawn_1.18.1-2.0.jar                 |Skeleton Horse Spawn          |skeletonhorsespawn            |2.0                 |COMMON_SET|Manifest: NOSIGNATURE
		balm-2.3.1+0.jar                                  |Balm                          |balm                          |2.3.1+0             |COMMON_SET|Manifest: NOSIGNATURE
		shulkerbox-1.18.1-1.0.0.jar                       |Advanced Shulkerboxes         |shulkerbox                    |1.18.1-1.0.0        |COMMON_SET|Manifest: NOSIGNATURE
		ninjaphenix-container-library-1.2.7+1.18.jar      |NinjaPhenix's Container Librar|ninjaphenix_container_lib     |1.2.7               |COMMON_SET|Manifest: NOSIGNATURE
		cloth-config-6.1.48-forge.jar                     |Cloth Config v4 API           |cloth_config                  |6.1.48              |COMMON_SET|Manifest: NOSIGNATURE
		stackrefill_1.18.1-2.1.jar                        |Stack Refill                  |stackrefill                   |2.1                 |COMMON_SET|Manifest: NOSIGNATURE
		1.18-enchantedgoldenapplecrafting-1.0.jar         |Enchanted Golden Apple Craftin|enchantedgoldenapplecrafting  |1.0                 |COMMON_SET|Manifest: NOSIGNATURE
		CraftableChainmail-1.18.1-3.0.0.jar               |Craftable Chainmail Armor     |craftablechainmail            |3.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		supermartijn642corelib-1.0.15a-mc1.18.jar         |SuperMartijn642's Core Lib    |supermartijn642corelib        |1.0.15a             |COMMON_SET|Manifest: NOSIGNATURE
		Highlighter-1.18.1-1.1.2.jar                      |Highlighter                   |highlighter                   |1.1.2               |COMMON_SET|Manifest: NOSIGNATURE
		simplybackpacks-1.18-2.0.0-build.25.jar           |Simply Backpacks              |simplybackpacks               |1.18-2.0.0-build.25 |COMMON_SET|Manifest: NOSIGNATURE
		Trapcraft-1.18.1-3.6.0.jar                        |Trapcraft                     |trapcraft                     |3.6.0               |COMMON_SET|Manifest: NOSIGNATURE
		curios-forge-1.18.1-5.0.3.0.jar                   |Curios API                    |curios                        |1.18.1-5.0.3.0      |COMMON_SET|Manifest: NOSIGNATURE
		Patchouli-1.18.1-61.jar                           |Patchouli                     |patchouli                     |1.18.1-61           |COMMON_SET|Manifest: NOSIGNATURE
		shulkerdropstwo_1.18.1-1.8.jar                    |Shulker Drops Two             |shulkerdropstwo               |1.8                 |COMMON_SET|Manifest: NOSIGNATURE
		EasyPaxelLite1.18.1(FORGE)vs1.0.6.jar             |Easy Paxel Lite               |easypaxellite                 |1.18.1-1.0.6        |COMMON_SET|Manifest: NOSIGNATURE
		collective-1.18.1-3.8.jar                         |Collective                    |collective                    |3.8                 |COMMON_SET|Manifest: NOSIGNATURE
		RingOfMiner-Forge-1.18.1-1.4.1.jar                |Ring of Miner                 |ring_of_miner                 |1.4.1               |COMMON_SET|Manifest: NOSIGNATURE
		time-in-a-bottle-2.1.0-mc1.18.1.jar               |Time In A Bottle              |tiab                          |2.1.0-mc1.18.1      |COMMON_SET|Manifest: NOSIGNATURE
		angelring-1.18-1.5.0.jar                          |Angel Ring                    |angelring                     |1.5.0               |COMMON_SET|Manifest: NOSIGNATURE
		firespreadtweaks_1.18.1-1.3.jar                   |Fire Spread Tweaks            |firespreadtweaks              |1.3                 |COMMON_SET|Manifest: NOSIGNATURE
		HappyTrails-1.18.1-1.39.0.8.jar                   |Happy Trails Mod              |happytrails                   |1.18.1-1.39.0.8     |COMMON_SET|Manifest: NOSIGNATURE
		RingOfEnderchest-Forge-1.18.1-1.4.1.jar           |Ring of Enderchest            |ring_of_enderchest            |1.4.1               |COMMON_SET|Manifest: NOSIGNATURE
		expandedstorage-7.3.3+1.18.jar                    |Expanded Storage              |expandedstorage               |7.3.3               |COMMON_SET|Manifest: NOSIGNATURE
		worldedit-mod-7.2.8.jar                           |WorldEdit                     |worldedit                     |7.2.8+6008-1246d61  |COMMON_SET|Manifest: NOSIGNATURE
		Project_MMO-1.18.1-3.67.2.jar                     |Project MMO                   |pmmo                          |1.18.1-3.67.2       |COMMON_SET|Manifest: NOSIGNATURE
		architectury-3.2.51.jar                           |Architectury                  |architectury                  |3.2.51              |COMMON_SET|Manifest: NOSIGNATURE
		1.18-StorageCabinet-1.4.2-forge.jar               |Storage Cabinet               |storagecabinet                |1.4.2               |COMMON_SET|Manifest: NOSIGNATURE
		moreoverlays-1.20.4-mc1.18.jar                    |More Overlays Updated         |moreoverlays                  |1.20.4-mc1.18       |COMMON_SET|Manifest: NOSIGNATURE
		globalxp-1.18.1-1.9.jar                           |Global XP                     |globalxp                      |1.9                 |COMMON_SET|Manifest: NOSIGNATURE
		reusable_rockets-1.18.1-1.0.0.jar                 |Reusable Rockets              |reusable_rockets              |1.18.1-1.0.0        |COMMON_SET|Manifest: NOSIGNATURE
		chunkloaders-1.1.7-mc1.18.jar                     |Chunk Loaders                 |chunkloaders                  |1.1.7               |COMMON_SET|Manifest: NOSIGNATURE
		FallingTree-1.18.1-2.16.0.jar                     |FallingTree                   |fallingtree                   |2.16.0              |COMMON_SET|Manifest: 3c:8e:df:6c:df:a6:2a:9f:af:64:ea:04:9a:cf:65:92:3b:54:93:0e:96:50:b4:52:e1:13:42:18:2b:ae:40:29
		infinitetrading_1.18.1-2.0.jar                    |Infinite Trading              |infinitetrading               |2.0                 |COMMON_SET|Manifest: NOSIGNATURE
		RingOfUnseen-Forge-1.18.1-1.2.1.jar               |Ring of Unseen                |ring_of_unseen                |1.2.1               |COMMON_SET|Manifest: NOSIGNATURE
		veinmining-forge-1.18-0.14.jar                    |Vein Mining                   |veinmining                    |1.18-0.14           |COMMON_SET|Manifest: NOSIGNATURE
		scaffoldingdropsnearby_1.18.1-1.6.jar             |Scaffolding Drops Nearby      |scaffoldingdropsnearby        |1.6                 |COMMON_SET|Manifest: NOSIGNATURE
		TradingPost-v3.0.0-1.18-Forge.jar                 |Trading Post                  |tradingpost                   |3.0.0               |COMMON_SET|Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		forgeautofish-4.0.0-1.18.x.jar                    |AutoFish for Forge            |forgeautofish                 |4.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		VanillaExcavators-1.18.1-4.0.0.jar                |Vanilla Excavators            |vanillaexcavators             |1.18.1-4.0.0        |COMMON_SET|Manifest: NOSIGNATURE
		biggerspongeabsorptionradius_1.18.1-1.6.jar       |Bigger Sponge Absorption Radiu|biggerspongeabsorptionradius  |1.6                 |COMMON_SET|Manifest: NOSIGNATURE
		EasyMagic-v3.2.0-1.18.1-Forge.jar                 |Easy Magic                    |easymagic                     |3.2.0               |COMMON_SET|Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		jei-1.18.1-9.1.0.44.jar                           |Just Enough Items             |jei                           |9.1.0.44            |COMMON_SET|Manifest: NOSIGNATURE
		justmobheads_1.18.1-5.3.jar                       |Just Mob Heads                |justmobheads                  |5.3                 |COMMON_SET|Manifest: NOSIGNATURE
		MerchantMarkers-1.18.1-1.1.0.jar                  |Merchant Markers              |merchantmarkers               |1.1.0               |COMMON_SET|Manifest: NOSIGNATURE
		goldenhopper-1.2.5-1.18.1.jar                     |Golden Hopper                 |goldenhopper                  |1.2.5               |COMMON_SET|Manifest: NOSIGNATURE
		Clumps-forge-1.18.1-8.0.2.jar                     |Clumps                        |clumps                        |8.0.2               |COMMON_SET|Manifest: NOSIGNATURE
		RingOfRepair-Forge-1.18.1-1.4.1.jar               |Ring of Repair                |ring_of_repair                |1.4.1               |COMMON_SET|Manifest: NOSIGNATURE
		journeymap-1.18-5.8.0alpha9.jar                   |Journeymap                    |journeymap                    |5.8.0alpha9         |COMMON_SET|Manifest: NOSIGNATURE
		awesomedungeon-1.1.4.jar                          |Awesome Dungeon               |awesomedungeon                |1.1.4               |COMMON_SET|Manifest: NOSIGNATURE
		NaturesCompass-1.18.1-1.9.3-forge.jar             |Nature's Compass              |naturescompass                |1.18.1-1.9.3-forge  |COMMON_SET|Manifest: NOSIGNATURE
		LibX-1.18.1-3.1.0.jar                             |LibX                          |libx                          |1.18.1-3.1.0        |COMMON_SET|Manifest: NOSIGNATURE
		anvilrestoration_1.18.1-1.2.jar                   |Anvil Restoration             |anvilrestoration              |1.2                 |COMMON_SET|Manifest: NOSIGNATURE
		charms-1.18-1.0.2.jar                             |Charms                        |charms                        |1.0                 |COMMON_SET|Manifest: NOSIGNATURE
		ClickMachine-1.18.1-6.0.0.jar                     |Click Machine                 |clickmachine                  |6.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		farsight-1.18-1.5.jar                             |Farsight mod                  |farsight_view                 |1.18-1.5            |COMMON_SET|Manifest: NOSIGNATURE
		passiveendermen_1.18.1-1.7.jar                    |Passive Endermen              |passiveendermen               |1.7                 |COMMON_SET|Manifest: NOSIGNATURE
		PackingTape-1.18-0.12.2.jar                       |Packing Tape                  |packingtape                   |0.12.2              |COMMON_SET|Manifest: NOSIGNATURE
		majruszsaccessories-1.18.1-0.4.0.jar              |Majrusz's Accessories         |majruszs_accessories          |0.4.0               |ERROR     |Manifest: NOSIGNATURE
		hidehands_1.18.1-1.5.jar                          |Hide Hands                    |hidehands                     |1.5                 |COMMON_SET|Manifest: NOSIGNATURE
		leashed-1.18.1-1.2.2.jar                          |Leashed                       |leashed                       |1.2.2               |COMMON_SET|Manifest: NOSIGNATURE
		AwesomeDungeonOcean-Forge-1.18-1.0.3.jar          |Awesome Dungeon Ocean         |awesomedungeonocean           |1.0.3               |COMMON_SET|Manifest: NOSIGNATURE
		client-1.18.1-20211210.034407-srg.jar             |Minecraft                     |minecraft                     |1.18.1              |COMMON_SET|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		MoreVanillaLib-1.18.1-3.0.0.jar                   |MoreVanillaLib                |morevanillalib                |1.18.1-3.0.0        |COMMON_SET|Manifest: NOSIGNATURE
		Jade-1.18-4.0.2.jar                               |Jade                          |jade                          |4.0.2               |COMMON_SET|Manifest: NOSIGNATURE
		forge-1.18.1-39.0.5-universal.jar                 |Forge                         |forge                         |39.0.5              |COMMON_SET|Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		BuildingWands-2.3_mc1.18-forge.jar                |Building Wands                |wands                         |2.3                 |COMMON_SET|Manifest: NOSIGNATURE
		RingOfGrowth-Forge-1.18.1-1.4.1.jar               |Ring of Growth                |ring_of_growth                |1.4.1               |COMMON_SET|Manifest: NOSIGNATURE
		EnchantmentMachine-1.18.1-1.0.11.jar              |Enchantment machine           |enchantmentmachine            |1.0.11-alpha+2021121|COMMON_SET|Manifest: NOSIGNATURE
		Iceberg-1.18.1-1.0.30.jar                         |Iceberg                       |iceberg                       |1.0.30              |COMMON_SET|Manifest: NOSIGNATURE
		EasyEmerald-Forge-1.18.1-1.3.2.jar                |Easy Emerald                  |easy_emerald                  |1.3.2               |COMMON_SET|Manifest: NOSIGNATURE
		Xaeros_Minimap_21.22.3.1_Forge_1.18.jar           |Xaero's Minimap               |xaerominimap                  |21.22.3.1           |COMMON_SET|Manifest: NOSIGNATURE
		assortedtech-1.18.1-2.1.0.jar                     |Assorted Tech                 |assortedtech                  |1.18.1-2.1.0        |COMMON_SET|Manifest: NOSIGNATURE
		baubley-heart-canisters-1.18-1.0.0.jar            |Baubley Heart Canisters       |bhc                           |1.18-1.0.0          |COMMON_SET|Manifest: NOSIGNATURE
		redoptions-1.18.1-1.0.0.5.jar                     |Red Options                   |redoptions                    |1.0.0.5             |COMMON_SET|Manifest: NOSIGNATURE
		StorageDrawers-1.18.1-10.0.0.jar                  |Storage Drawers               |storagedrawers                |10.0.0              |COMMON_SET|Manifest: NOSIGNATURE
		VanillaHammers-1.18.1-4.0.0.jar                   |Vanilla Hammers               |vanillahammers                |1.18.1-4.0.0        |COMMON_SET|Manifest: NOSIGNATURE
		AmbientEnvironment-forge-1.18.1-7.0.3.jar         |Ambient Environment           |ambientenvironment            |7.0.3               |COMMON_SET|Manifest: NOSIGNATURE
		ItemsDontBreak-1.18-0.5.0.jar                     |Items Don't Break             |itemsdontbreak                |0.5.0               |COMMON_SET|Manifest: NOSIGNATURE
		moredragoneggs-3.1.jar                            |More Dragon Eggs              |moredragoneggs                |3.1                 |COMMON_SET|Manifest: NOSIGNATURE
		PuzzlesLib-v3.0.2-1.18-Forge.jar                  |Puzzles Lib                   |puzzleslib                    |3.0.2               |COMMON_SET|Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		grindstonesharpertools_1.18.1-1.7.jar             |Grindstone Sharper Tools      |grindstonesharpertools        |1.7                 |COMMON_SET|Manifest: NOSIGNATURE
	Crash Report UUID: cec949b2-4253-4e44-9513-bb2d77ab9dab
	FML: 39.0
	Forge: net.minecraftforge:39.0.5

**Comment by Majrusz** [comment]
As far as I can see you do not have Majrusz Library installed

**Comment by DSAH1997** [comment]
Hmm strange, I did download it. Ill have to check my mod folders file, might of not transferred over.

**Comment by DSAH1997** [comment]
yeah, was still in the .minecraft folder, must of missed it when moving the files into my mods folder, Thank you for your time,

**Comment by Majrusz** [comment]
You are welcome :)
