### ISSUE TITLE
Local Server Crash when opening world

### ISSUE THREAD

**Issue by GolfinhoVoador** [Majrusz/MajruszsAccessories#20]
This is happening in Minecraft 1.20.1 with Majrusz's Accessories 1.2.3 and  Majrusz Library 5.1.1
Im almost certain that this is an incompatibility with [Kintsugi](https://www.curseforge.com/minecraft/mc-mods/kintsugi), a mod that modifies the librarian's trades and also does other things with enchantments (I tested with only Majrusz's Accessories, Library and Kintsugi, and it crashed, without Kintsugi it worked fine)

Crash log(s):
[crash-2023-09-19_20.10.33-server.txt](https://github.com/Majrusz/MajruszsAccessories/files/12667260/crash-2023-09-19_20.10.33-server.txt) 
[crash-2023-09-19_20.24.13-server.txt](https://github.com/Majrusz/MajruszsAccessories/files/12667263/crash-2023-09-19_20.24.13-server.txt)
[crash with only the two mods enabled](https://github.com/Majrusz/MajruszsAccessories/files/12667377/crash-2023-09-19_20.45.27-server.txt)

**Comment by Majrusz** [comment]
Hello, it should be fixed with the latest 1.3.0 release
