### ISSUE TITLE
Bugged accessory when combining accessories

### ISSUE THREAD

**Issue by R3TR0xSN1P3R** [Majrusz/MajruszsAccessories#21]
Version 1.20.1
sometimes when combining trinkets it comes out to a null/0 value
![image_2023-10-13_155236821](https://github.com/Majrusz/MajruszsAccessories/assets/88951606/bc317d8a-0e91-4242-8ffb-285dcd6d9c06)
![image_2023-10-14_192546932](https://github.com/Majrusz/MajruszsAccessories/assets/88951606/9d4aef06-a223-48d3-95ee-ea4e29816e81)

sometimes it also has no value rather than the ghost value its showing if i find another one ill post it but i have this picture on hand let me know what other info you need
updated to show an actual broken item that doesnt have a stat

**Comment by RECCASTWIN** [comment]
yeah I got the same bug
![image](https://github.com/Majrusz/MajruszsAccessories/assets/91829887/c127a6c2-c69d-4581-b74f-66c71acb3f16)

**Comment by Majrusz** [comment]
Hello, thanks for the report, it should be fixed with the latest 1.3.0 release
