### ISSUE TITLE
Bugged accessories when combining

### ISSUE THREAD

**Issue by RECCASTWIN** [Majrusz/MajruszsAccessories#22]
it's basically the same as R3TR0xSN1P3R's issue where combining things breaks aforementioned things
![image](https://github.com/Majrusz/MajruszsAccessories/assets/91829887/bac6d764-cb0a-4937-8a39-0f3756d6537a)

**Comment by RECCASTWIN** [comment]
The combining works, but it breaks because of Crafting Tweaks by BlayTheNinth
![image](https://github.com/Majrusz/MajruszsAccessories/assets/91829887/fd3051b8-eaf0-4918-b560-d7e7c6ab531c)

**Comment by Majrusz** [comment]
Hello, thanks for the report, as it is a duplicate of this https://github.com/Majrusz/MajruszsAccessories/issues/21 I will close this one
