### ISSUE TITLE
Game crashes when using "discount Voucher" item and attempting to trade with an Easy Villagers trading block.

### ISSUE THREAD

**Issue by Clonephaze** [Majrusz/MajruszsAccessories#25]
The [Easy Villagers](https://www.curseforge.com/minecraft/mc-mods/easy-villagers) mod has a block called the [Trader Block](https://github.com/henkelmax/easy-villagers/blob/master/src/main/java/de/maxhenkel/easyvillagers/blocks/TraderBlock.java). After looking into both class files and looking at the [crash log](https://pastebin.com/1iPg7aHa) it seems like the issue might be coming from [this line](https://github.com/Majrusz/MajruszsAccessories/blob/01eaf8b755fdf32aa0c806e707e6460fb4cb761e/common/src/main/java/com/majruszsaccessories/accessories/components/TradingDiscount.java#L50) in your TradingDiscount class. The crash log indicates a ClassCastException when attempting to cast a ClientLevel to a ServerLevel, and it specifies that class specifically. Not entirely sure if that's something that should be fixed in the TradingDiscount class or in the OnTradesUpdated class from your library mod or an entirely different class. Never actually worked with java or I'd try fixing it and sending a PR lol. Let me know if you need other info. 

Also the issue was first reported [here,](https://github.com/ChosenArchitect/ChosensModdedAdventure/issues/57) as far as I know.

**Comment by Majrusz** [comment]
Hello, thanks for the report. I fixed it on my side here ec62f0319d1445c743e1bd80e3980bd9633bbb60 and soon will release new version
