### ISSUE TITLE
Randomized preview item given as crafting result

### ISSUE THREAD

**Issue by NekoLeila** [Majrusz/MajruszsAccessories#28]
I combined 2 Discount Vouchers in my inventory (I usually do it in a crafting table) and instead of getting a normal one back, I got the [+56%~+60%] preview one in my inventory and when I try to combine it with another Discount Voucher, it acts like a much lower % one than I had before

![Untitled](https://github.com/Majrusz/MajruszsAccessories/assets/123903504/1e17fad2-e088-46d6-a166-b3a83f10cfd7)

**Comment by NekoLeila** [comment]
Went from 58% down to what I'm guessing is counting as 0% T_T

**Comment by NekoLeila** [comment]
I really love your mods, tho. Thank you for all the work you do. <3

**Comment by Majrusz** [comment]
Hello thanks for the report, I fixed it in library mod https://github.com/Majrusz/MajruszLibrary/pull/53/commits/ed362997e4fbb0df69e5d6351ebbcac4d962a3ff and soon new version will be available
