### ISSUE TITLE
Some modded pickaxes don't work with the lucky rock

### ISSUE THREAD

**Issue by Not-February** [Majrusz/MajruszsAccessories#3]
A friend tells me that this is because the code in this mod checks for 'pickaxe' in the item's registry name for whether an item can drop while mining with a tool.

This mostly becomes problematic with mods like Tetra, in which the pickaxe is just one of many variants of a tool which doesn't have pickaxe in the registry name, and recently I have noticed that Botania's manasteel pickaxe *also* doesn't have 'pickaxe' in its registry name (it is botania:manasteel_pick on at least the 1.18 versions).

Versions I'm noticing this with for what it's worth:

``Minecraft 1.18.1``
``Forge 39.1.2``
``Majrusz Library 2.7.1``
``Majrusz's Accessories 0.4.1``
``Curios API 5.0.6.2``

**Comment by Majrusz** [comment]
Thanks for the report, fixed in the latest rework
