### ISSUE TITLE
[Forge 1.20.1] Occassional Crash on startup.

### ISSUE THREAD

**Issue by PlayfulPiano** [Majrusz/MajruszsAccessories#30]
Doesn't happen every instance load, but does seem to happen pretty frequently.

Crash report;
[crash-2023-11-21_01.46.29-client.txt](https://github.com/Majrusz/MajruszsAccessories/files/13422638/crash-2023-11-21_01.46.29-client.txt)

**Comment by Majrusz** [comment]
Hello, thanks for the report, it got fixed with the latest release
