### ISSUE TITLE
Rhino incompatibility ?

### ISSUE THREAD

**Issue by 3dEADto2** [Majrusz/MajruszsAccessories#32]
I updated Majrusz Library from 6.1.3 to 6.1.7 and Majrusz's Accessories from 1.3.2 to 1.3.3. Now the game crashes on startup. (Latest log: https://pastebin.com/JKsrrWMJ).  I think it might be an incompatibility between majrusz and rhino because I get errors like `[STDERR]: [Rhino] Failed to get declared methods for net.minecraft.class_310: java.lang.RuntimeException: Mixin transformation of net.minecraft. class_636 failed` or `[STDERR]: [Rhino] Failed to get declared fields for net.minecraft.class_310: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_636 failed`. These do not occur if majrusz mods are disabled.

**Comment by Majrusz** [comment]
Hello, thanks for the report, it got fixed with the latest 6.1.8 library release

**Comment by 3dEADto2** [comment]
No problem. Thanks for the great mod and the fast update =)
