### ISSUE TITLE
Display issue with Adventure kit accessory perk.

### ISSUE THREAD

**Issue by Lovux** [Majrusz/MajruszsAccessories#34]
With the most recent version of the Majrusz's Accessories, there is a display bug with the Adventure kit modifier that affects the Adventure kit, Adventurer Rune, and the Soul of Minecraft; no matter how far away you are from a bed, the (% in total) never rises above 0%. I have done some testing and I believe it still works how it should, but I can't be 100% certain. I have attached a picture below of the Adventure Kit.
![adventure kit display issue](https://github.com/Majrusz/MajruszsAccessories/assets/13266853/c93cb942-dde6-4e3f-95d5-fe979084afdb)

**Comment by Majrusz** [comment]
Hello, thanks for the report, I fixed it with the latest 7.0.0 library release
