### ISSUE TITLE
[1.19.2]: Missing `Pocket` texture

### ISSUE THREAD

**Issue by SiverDX** [Majrusz/MajruszsAccessories#45]
**Version**: 1.4.0-backport.1

![image](https://github.com/Majrusz/MajruszsAccessories/assets/22003703/5b478256-9d45-4e69-b0ec-dbb3deaa1a8a)

Test instance (`Xaero's Minimap` and `Xaero's World Map` is also present here):
![image](https://github.com/Majrusz/MajruszsAccessories/assets/22003703/dc7381ac-f8c0-4298-aa51-1d67e698729d)

**Comment by SiverDX** [comment]
using `TextureStitchEvent.Pre` fixed the issue

**Comment by Majrusz** [comment]
Hello, thanks for the report, I fixed it and released a new backport with that fix included 4e7a3a495d40067e4da9bc7023bb5968ab32e2fd
