### ISSUE TITLE
Issue with Accessories tagging, KubeJS, FTB Quests (Forge, 1.19.2)

### ISSUE THREAD

**Issue by katubug** [Majrusz/MajruszsAccessories#49]
Hi! My co-developer was trying to write a quest explaining the basics of your mod, using the latest version with the 1.20 backport items.

They used KubeJS to add a "forge:majrusz_accessories" tag to many of the mod items, and then added an FTB Quest to require one of the items in that tag - something we do frequently. Unfortunately, the tag shows as broken and containing no items, despite the fact that the items ingame show that the tag has been added.

We then attempted to make a quest using one of your items and selected the "curios:pocket" tag, which also showed as broken. We then tested using an item from the Artifacts mod, and it worked correctly. We figure the issue must have something to do with the way your items are using tags, but we're not sure what could be different. I confirmed that everything was done correctly on their end, and we also combed through the latest.log and found nothing special about tags not loading, or anything to do with the word "majrusz."

Let me know if there's any other information we can provide, such as if you need the log or anything. Thanks for your time!

**Comment by Emmulah** [comment]
latest.log in question
![2024-03-05_14 47 57](https://github.com/Majrusz/MajruszsAccessories/assets/136125481/9e5b573b-fb28-487c-94c4-544f318f8402)


[latest.log](https://github.com/Majrusz/MajruszsAccessories/files/14501367/latest.log)

**Comment by SiverDX** [comment]
`Not all defined tags for registry ResourceKey[minecraft:root / minecraft:item] are present in data pack: forge:maj_accessories`

> They used KubeJS to add a "forge:majrusz_accessories" tag

maj != majrusz

I'm assuming you also did sth. wrong when using the `pocket` tag
https://www.curseforge.com/minecraft/mc-mods/lmft for more info about broken tags

**Comment by katubug** [comment]
Hi, just a few things to clarify



1) The curios:pocket tag is not one that we created.



2) We experimented with multiple tags, including the two mentioned
("majrusz_accessories" and "maj_accessories"), and "maj_acs."


3) I am familiar with LMFT but didn't see any "failed to load tag" stuff in
the log. I haven't seen that error you quoted before, do you know what it
means?


With regards to the second point, we did notice that when we replaced
"majrusz_accessories" with "maj_acs," both tags were visible on the item.
This should not have been the case, because we literally replaced one piece
of text with the other, and then did /reload.


It's possible it was a KubeJS glitch, but since it only occurs with items
from your mod, I think it's something else.

**Comment by SiverDX** [comment]
just to clarify: not my mod, just another user

if the `curios:pocket` tag was empty / broken then you wouldn't be able to equip the items themselves into said slot
it is a very normal implementation which is the same for all curios items

sounds like a configuration issue on your end / issue from ftb quest

**Comment by katubug** [comment]
I see. I appreciate you trying to help, but I think this issue is something
the mod dev might need to weigh in on.

The curios equip just fine. Additionally, making an FTB Quest for curios
tags - using a curio from a different mod - works just fine. It's ONLY tags
attached to items from this mod which are seeming broken.

When creating a quest, we started with a Majrusz curio and chose "Convert
to Tag Item." Normally this shows all the items in that tag, rotating, in
the preview. What is happening here instead is that it shows the FTB Quests
purple question mark, and clicking it gives an "invalid tag" notice. This
happens with our KubeJS tags and the built in Curios tags. Again, only to
items from this mod.

That's why I think there might be an issue with the way the items in this
mod load tags, which only the mod dev could confirm.

**Comment by Emmulah** [comment]
to be completely clear: the tag "works" in the sense that things which have this tag can be searched and referenced using this tag. But as Katu said, we just get a broken texture when using the tag in FTB Quests. this is the code in question, placed in the item section of my kubejs tags file:

// Majrusz's Accessories

event.add('forge:maj_acs',
'majruszsaccessories:certificate_of_taming',
'majruszsaccessories:idol_of_fertility',
'majruszsaccessories:lucky_rock',
'majruszsaccessories:tamed_potato_beetle',
'majruszsaccessories:angler_trophy',
'majruszsaccessories:discount_voucher',
'majruszsaccessories:dream_catcher',
'majruszsaccessories:metal_lure',
'majruszsaccessories:miner_guide',
'majruszsaccessories:adventurer_kit',
'majruszsaccessories:tool_scraps',
'majruszsaccessories:unbreakable_fishing_line',
'majruszsaccessories:adventurer_rune',
'majruszsaccessories:angler_rune',
'majruszsaccessories:household_rune',
'majruszsaccessories:miner_rune',
'majruszsaccessories:nature_rune',
'majruszsaccessories:soul_of_minecraft',
'majruszsaccessories:secret_ingredient',
'majruszsaccessories:swimmer_guide'
)

// Majruzs's Boosters
event.add('forge:maj_boosters',
'majruszsaccessories:onyx',
'majruszsaccessories:dice',
'majruszsaccessories:owl_feather',
'majruszsaccessories:golden_dice',
'majruszsaccessories:golden_horseshoe',
'majruszsaccessories:horseshoe'
)

// Majruzs's Cards
event.add('forge:maj_cards',
'majruszsaccessories:gambling_card',
'majruszsaccessories:removal_card',
'majruszsaccessories:reverse_card'
)

**Comment by SiverDX** [comment]
you might be better off asking the ftb (quest / itemfilter) team about their filter implementation

https://github.com/latvian-dev/item-filters/blob/41edd14ae270bd32fa34b3281e8221148e8fe97f/common/src/main/java/dev/latvian/mods/itemfilters/item/TagFilterItem.java#L66

![image](https://github.com/Majrusz/MajruszsAccessories/assets/22003703/a67a4553-8cad-4d0e-9080-054b7a4ac538)


![image](https://github.com/Majrusz/MajruszsAccessories/assets/22003703/872df146-4e3e-4595-9218-a012b1249981)

**Comment by Emmulah** [comment]
I appreciate your willingness to help, but as it is exclusively this mod that we have the problem with, and we've tested many variables, we'd just like to confer with the mod dev on this issue. Thanks.

**Comment by SiverDX** [comment]
i'm assuming its due to missing creative tab entries

https://github.com/latvian-dev/item-filters/blob/41edd14ae270bd32fa34b3281e8221148e8fe97f/common/src/main/java/dev/latvian/mods/itemfilters/DisplayStacksCache.java#L39-L48

you cant find the items through the search and that seems to be a criteria for the filters

**Comment by Majrusz** [comment]
Hello, I am not very familiar with how KubeJS and FTB Quests work, but I can confirm that accessories in my mod are added in a custom way to have multiple copies of the same accessory with different tags. @SiverDX discovered that these mods filter items based on their visibility in search bar in creative mode menu and thats where we have incompatibility. Thank you all for reporting that, I will prepare a compatibility fix within next few days

**Comment by katubug** [comment]
Thanks for your response! Glad we could get this sorted! :D

**Comment by Majrusz** [comment]
I have made all items properly accessible through creative mode menu ad0911f805038f673cb951263d7b0dd5f1bd29f9 and released a new backport version. It should fix your issues, but I keep the thread opened until you confirm it
