### ISSUE TITLE
Marge Duplicates Accessories for Better Efficiency Bonus [enhancement]

### ISSUE THREAD

**Issue by Orange-Peel-Assassin** [Majrusz/MajruszsAccessories#5]
I have two lucky rocks one of them has a +1% Efficiency Bonus and the other has a +6% Efficiency Bonus. It would be cool if I could marge them to have one lucky rock with a +7% Efficiency Bonus.

**Comment by Majrusz** [comment]
Hi, sorry for the late response. It was introduced in the latest 1.1.0 release
