### ISSUE TITLE
[Forge - 1.19.2]: Decoration renders above tooltip in recipe viewer

### ISSUE THREAD

**Issue by SiverDX** [Majrusz/MajruszsAccessories#52]
Version: 1.5.2

Using EMI: https://www.curseforge.com/minecraft/mc-mods/emi

![image](https://github.com/Majrusz/MajruszsAccessories/assets/22003703/920f5e95-f320-4845-89a1-0c165ff7001b)

**Comment by SiverDX** [comment]
I'll throw this in here:

It also renders above the stack count (at least in [Sophisticated Backpacks](https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks))

![image](https://github.com/Majrusz/MajruszsAccessories/assets/22003703/6fa80ffb-30ac-47fc-8584-92b440db0e49)

**Comment by Majrusz** [comment]
Hello, thanks for the report! I fixed it with c92339218cc1b15f03b6de10250a5ef88bfa1c6a and released a new backport version
