### ISSUE TITLE
[Fabric 1.20.1] crash when trying to merge 2 trinkets together

### ISSUE THREAD

**Issue by memphismc** [Majrusz/MajruszsAccessories#55]
[crash-2024-04-23_19.09.05-client.txt](https://github.com/Majrusz/MajruszsAccessories/files/15079734/crash-2024-04-23_19.09.05-client.txt)

**Comment by Majrusz** [comment]
Hello, thanks for the report, I have fixed it 431ae2afff173539060a82833118560cc91fcd79 and released a new version
