### ISSUE TITLE
[Forge 1.20.1] Incompatibility With Aquaculture 2

### ISSUE THREAD

**Issue by LilChromie** [Majrusz/MajruszsAccessories#57]
I saw another entry listing an Aquaculture 2 incompatibility for a previous version, and wanted to note that it applies to 1.20.1 as well.

In addition to the drop issue regarding the fishing line and the trophy, the accessory boosts do not apply when using aquaculture 2 fishing rods. I have confirmed that the 1.18.2 version of the mod was compatible with aquaculture, however.

**Comment by Majrusz** [comment]
Hello, thanks for the report, I fixed it with the latest library version https://github.com/Majrusz/MajruszLibrary/commit/5fbdce123e93d2acf2269ebc13f6e247313d3a73

**Comment by LilChromie** [comment]
Hello thanks for the quick response. Upon making sure I am on the latest version (both accessories and library), I ran a few tests and discovered a few things: 

In the neoforge version, (majrusz-library-neoforge-1.20.1-7.0.6), nothing works when using aquaculture 2 fishing rods. The accessories do not drop, and when equipped they do not work (tested by boosting the accessories to drop and activate 100% of the time, and tested individually with the base items, angler rune, and soul of minecraft).

In the forge version (majrusz-library-forge-1.20.1-7.0.6, ran using the same version of neoforge as the prior tests) there is some compatibility, but there are still issues. The accessories are dropping when using aquaculture rods, and the double drops function properly. However, the fishing time reduction does not work with aquaculture rods, and the purple particle effects caused by the rune do not appear. I cannot confirm if the luck boost works or not, because despite increasing it to 16 I could not notice a difference when using it with either vanilla or aquaculture mods, however I might just not know how luck works. (Again, tested by boosting the accessories to drop and activate 100% of the time, and tested individually with the base items, angler rune, and soul of minecraft).

**Comment by LilChromie** [comment]
also in case it's relevant, I ran these tests using neoforge version 47.1.104 for minecraft 1.20.1.

**Comment by Majrusz** [comment]
Hello, thanks for the report, I have fixed it and it should work properly with the latest 7.0.7 library version. I will keep the thread open for now in case you find other incompatibilities

**Comment by LilChromie** [comment]
After installing the latest version of library, the game now crashes if ran alongside aquaculture 2. This holds true for both the forge and neoforge versions. Crash reports attached below.
[crash-2024-04-27_21.28.58-client.txt](https://github.com/Majrusz/MajruszsAccessories/files/15140457/crash-2024-04-27_21.28.58-client.txt)
[crash-2024-04-27_21.28.00-client.txt](https://github.com/Majrusz/MajruszsAccessories/files/15140458/crash-2024-04-27_21.28.00-client.txt)

**Comment by LilChromie** [comment]
also I was only running library, accessories, and aquaculture 2 when the crashes happened

**Comment by Majrusz** [comment]
Damn mixins, thanks for the report, it should work fine with 7.0.8 now

**Comment by LilChromie** [comment]
Can't currently test whether the aquaculture crash is gone because now Library crashes on its own. Not even generating a report for me. Trying to fix this bug seems like a nightmare lol.

**Comment by LilChromie** [comment]
All right, after using the new, proper 7.0.8 file everything seems to be working fine on both the forge and neoforge versions. I think you can mark this issue as closed now. Thanks for all the help!

**Comment by Majrusz** [comment]
Great to hear that, thanks!
