### ISSUE TITLE
[1.18] Mod Doesn't Work on 1.18.2

### ISSUE THREAD

**Issue by PhweeDev** [Majrusz/MajruszsAccessories#6]
I am making this issue since you cannot play this mod on 1.18.2. Only 1.18.1. Can you quickly port the mod to 1.18.2 so it works?

Report (if you need it): https://paste.gg/p/anonymous/0d6f4d9815e54c1eb983d079cdeb5cea

**Comment by PhweeDev** [comment]
How's the "port" going, if it's been worked on?

**Comment by Majrusz** [comment]
Sorry to inform, but I have decided to not support any older version. It takes me too much time to backport certain features especially when some of them were implemented by Mojang in 1.19
